### ISSUE TITLE
Attribute error - when considering somatic variants in the context of tumour and normal BAM files

### ISSUE THREAD

**Issue by skanwal** [bjpop/snvly#2]
Hi Bernie,

Firstly, thanks for the great tool.

I have started testing it with one of our internal datasets and currently using the first example command for considering somatic variants in the context of tumour and normal BAM files in the following [section](https://github.com/bjpop/snvly/blob/b3aa473356d3b13382348016574e7c2cdfdb71f2/README.md#example-usage).

I am using the following command to invoke snvly:

```
snvly --sample P025 --labels tumour normal -- tumor-ready.bam normal-ready.bam < 0000.vcf > variants.snvly.csv
```
However, it produces a bunch of warning such as:

```
WARNING:root:Skipping variant: chr7:68704980,A>AG
WARNING:root:Skipping variant: chr7:73127599,GA>G
WARNING:root:Skipping variant: chr7:111726667,A>AATT
WARNING:root:Skipping variant: chr7:111726694,ATTCT>A
.
.
.
```

And then the following error:

```
Traceback (most recent call last):
  File "/virtual_envs/snvly_dev/bin/snvly", line 11, in <module>
    load_entry_point('snvly==0.1.0.0', 'console_scripts', 'snvly')()
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 415, in main
    process_variants_bams(options, regions, variants)
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 175, in process_variants_bams
    write_output_row(chrom, pos, ref, alt, pos_normalised, options.sample, region_counts, bams_features)
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 181, in write_output_row
    row_bams = [str(x) for bam in bam_features for x in bam.as_list()]
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 181, in <listcomp>
    row_bams = [str(x) for bam in bam_features for x in bam.as_list()]
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 311, in as_list
    self.alt_read_features.as_list() + \
  File "/virtual_envs/snvly_dev/lib/python3.7/site-packages/snvly/snvly.py", line 268, in as_list
    alt_count = getattr(self, self.alt)
AttributeError: 'BaseCounts' object has no attribute 'AT'
```

Could this be specific to my input data? Also, does snvly only consider point mutations?
Any help will be greatly appreciated.

----
Sehrish K.

**Comment by bjpop** [comment]
Thanks @skanwal 

I should note that snvly has now been renamed to Varlap:

   https://github.com/bjpop/varlap

If you have INDELs that you want to process then please try the indels branch which is currently under development:

    https://github.com/bjpop/varlap/tree/indels

Note that some of the command line arguments have changed in the move to varlap.

Can you please try your sample again with varlap and let me know if the bug persists?

**Comment by skanwal** [comment]
Followed-up in the issue above.
